title: BAIN Lerntagebuch
author: Adrian Menti
email: adrian.menti@stud.fhgr.ch 
description: > # this means @stud.fhgr.ch to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  Menti696 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
